<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/iLogos/logo_novafct.png" width="200">

# Departamento de Engenharia Mecânica e Industrial
## Mecânica Aplicada I 

## EQUILÍBRIO DA PARTÍCULA NO ESPAÇO

### Problema 8

Uma placa retangular está suportada por três cabos conforme é indicado na figura. Sabendo que a força de tração instalada no cabo AC é de 60 N, determine o peso da placa.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch02/P8/MAI_Ch02_P8.png"
style="width: 20%; max-width: 100%;"/>

#### Objectivos de aprendizaem

- Conseguir expressar as componentes cartesianas de uma força no espaço.

- Conseguir estabelecer as equações de equilíbrio de uma partícula no espaço.



### Resolução

Comece-se por assumir que a força de reação no ponto A é igual em módulo ao peso próprio da placa (desprezando-se assim o peso próprio dos cabos). O diagrama de corpo livre da partícula no ponto A permite representar todas as forças concorrentes envolvidas no equilíbrio estático:

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch02/P8/MAI_Ch02_P8a.jpg"
style="width: 20%; max-width: 100%;"/>

A condição de equilíbrio da partícula do espaço pressupõe:

\begin{equation*}
\sum \vec{F} = \vec{0}\Leftrightarrow
\vec{T}_\textrm{AB} + \vec{T}_\textrm{AC} + \vec{T}_\textrm{AD} + \vec{P} =
\vec{0}
\end{equation*}

Contudo, para desenvolver adequadamente este sistema de equações é necessário conhecer  as componentes cartesianas dos vetores de força aplicados em A. Para tal é  necessário desenvolver as seguintes quantidades vetoriais:

\begin{equation*}
\begin{cases}
\vec{T}_\textrm{AB} = T_\textrm{AB}\vec{\lambda}_\textrm{AB} \\
\vec{T}_\textrm{AC} = T_\textrm{AC}\vec{\lambda}_\textrm{AC} \\
\vec{T}_\textrm{AD} = T_\textrm{AD}\vec{\lambda}_\textrm{AD} \\
\vec{P} = P \vec{\jmath}
\end{cases}
\end{equation*}

em que os versores $\vec{\lambda}$ definem a direção e sentido onde atuam as respetivas forças. Assim sendo, é necessário conhecer os cossenos diretores associados a estes versores em relação ao sistema de coordenadas escolhido $S(0,\vec{\imath},\vec{\jmath},\vec{k})$.

É importante recordar, neste ponto, que a direcção de uma força qualquer no
espaço pode ser definida pelas coordenadas de dois pontos pelos quais passa a
sua linha de acção, $M(x_1,y_1,z_1)$ e $N(x_2,y_2,z_2)$.

\begin{equation*}
\begin{aligned}
\vec{F} &= F \vec{\lambda}
\quad\wedge\quad
\vec{\lambda} = \frac{\vec{F}}{F} = \frac{\vec{MN}}{||\vec{MN}||}
= \frac{1}{d}(d_x\vec{\imath}+d_y\vec{\jmath}+d_z\vec{k})
\end{aligned}
\end{equation*}

com,

\begin{equation*}
\begin{aligned}
d_x &= x_2 - x_1 \\
d_y &= y_2 - y_1 \\
d_z &= z_2 - z_1 \\
d &= \sqrt{d_x^2 + d_y^2 + d_z^2}
\end{aligned}
\end{equation*}



Para tal faça-se:

- Pontos:

\begin{equation*}
\begin{aligned}
&A(0,480,0)~;~
B(-320,0,360)\\
&C(450,0,360)~;~
D(250,0,-360)
\end{aligned}
\end{equation*}

In [2]:
import numpy as np

A = [0,480,0] # unit: mm
B = [-320,0,360]
C = [450,0,360]
D = [250,0,-360]

- Vetores - componentes cartesianos:

\begin{equation*}
\vec{AB} = \vec{OB} - \vec{OA} = (-320,0,360) - (0,480,0) = -320\vec{\imath} -480 \vec{\jmath} + 360
\vec{k}\\
\end{equation*}

In [3]:
vAB = np.subtract(B,A); print('vAB = ',vAB)


vAB =  [-320 -480  360]


\begin{equation*}
\vec{AC} = \vec{OC} - \vec{OA} = (450,0,360) - (0,480,0) = 450\vec{\imath} -480 \vec{\jmath} + 360
\vec{k}\\
\end{equation*}

In [4]:
vAC = np.subtract(C,A); print('vAC = ',vAC)

vAC =  [ 450 -480  360]


\begin{equation*}
\vec{AD} = \vec{OD} - \vec{OA} = (250,0,-360) - (0,480,0) = 250\vec{\imath} -480
\vec{\jmath} - 360 \vec{k}\\
\end{equation*}

In [5]:
vAD = np.subtract(D,A); print('vAD = ',vAD)

vAD =  [ 250 -480 -360]


- Vetores - módulos:

Por definição de norma de um vetor genérico $\vec{v}$:
\begin{equation*}
||\vec{v}|| = \sqrt{\vec{v}\cdot\vec{v}} =
\sqrt{v_x^2 + v_y^2 + v_z^2}\\
\end{equation*}

Pelo que,

\begin{equation*}
||\vec{AB}|| = \sqrt{(-320)^2+(-480)^2+ 360^2} = 680~\textrm{mm}\\
\end{equation*}

In [6]:
modAB = np.sqrt(np.dot(vAB,vAB))
print('modulo de AB = ','{:.1f}'.format(modAB),' mm')

modulo de AB =  680.0  mm


\begin{equation*}
||\vec{AC}|| = \sqrt{450^2+(-480)^2 + 360^2}=
750~\textrm{mm}\\
\end{equation*}

In [7]:
modAC = np.sqrt(np.dot(vAC,vAC))
print('modulo de AC = ','{:.1f}'.format(modAC),' mm')


modulo de AC =  750.0  mm


\begin{equation*}
||\vec{AD}|| = \sqrt{250^2+(-480)^2
+(- 360)^2} =  650~\textrm{mm}\\
\end{equation*}

In [8]:
modAD = np.sqrt(np.dot(vAD,vAD))
print('modulo de AD = ','{:.1f}'.format(modAD),' mm')

modulo de AD =  650.0  mm


Assim sendo os vetores das forças aplicadas em A vêm:

\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AB} = T_\textrm{AB}\vec{\lambda}_\textrm{AB}
= T_\textrm{AB}\frac{\vec{AB}}{||\vec{AB}||} =
T_\textrm{AB}(-0.471 \vec{\imath} -0.706 \vec{\jmath} + 0.529 \vec{k})
\end{aligned}
\end{equation*}

In [9]:
np.set_printoptions(precision=3)
verAB = vAB/modAB
print('verAB = ',verAB)


verAB =  [-0.471 -0.706  0.529]


\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AC} = T_\textrm{AC}\vec{\lambda}_\textrm{AC}
= T_\textrm{AC}\frac{\vec{AC}}{||\vec{AC}||} =
T_\textrm{AC}(0.6 \vec{\imath} -0.64 \vec{\jmath} + 0.48 \vec{k})
\end{aligned}
\end{equation*}

In [10]:
np.set_printoptions(precision=3)
verAC = vAC/modAC
print('verAC = ',verAC)


verAC =  [ 0.6  -0.64  0.48]


\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AD} = T_\textrm{AD}\vec{\lambda}_\textrm{AD}
= T_\textrm{AD}\frac{\vec{AD}}{||\vec{AD}||} =
T_\textrm{AD}(0.385 \vec{\imath} -0.738  \vec{\jmath} - 0.554 \vec{k})
\end{aligned}
\end{equation*}

In [11]:
np.set_printoptions(precision=3)
verAD = vAD/modAD
print('verAD = ',verAD)

verAD =  [ 0.385 -0.738 -0.554]


Resulta finalmente o seguinte sistema de equações do equilibrio estático da partícula A:


Esta equação vetorial pode ser decomposta em três equações esclares de acordo com as componentes dos vetores segundo os eixos do referencial cartesiano escolhido:

\begin{equation*}
\begin{cases}
\sum F_x = 0\\
\sum F_y = 0\\
\sum F_z = 0
\end{cases}
\Leftrightarrow
\begin{cases}
-0.471\,T_\textrm{AB} + 0.385\,T_\textrm{AD} +0.6\,T_\textrm{AC} = 0\\
- 0.706\,T_\textrm{AB} - 0.64\,T_\textrm{AC} - 0.738\,T_\textrm{AD}  + P =
 0\\
0.529\,T_\textrm{AB} + 0.48\,T_\textrm{AC} - 0.554\,T_\textrm{AD} = 0
\end{cases}
\end{equation*}

desenvolvendo,

\begin{equation*}
\begin{cases}
-0.471\,T_\textrm{AB} + 0.6\,T_\textrm{AC} = -0.385\,T_\textrm{AD} \\
- 0.706\,T_\textrm{AB} - 0.64\,T_\textrm{AC} + P =
   0.738\,T_\textrm{AD}  \\
0.529\,T_\textrm{AB} + 0.48\,T_\textrm{AC}  = 0.554\,T_\textrm{AD}
\end{cases}
\end{equation*}

In [12]:
import sympy as sy
from sympy.solvers import solve

TAC = 60 # unit: N
tab, tad, p = sy.symbols('tab tad p')

EQX = tab*verAB[0] + TAC*verAC[0] + tad*verAD[0]
print('EQX : ',EQX)
EQY = tab*verAB[1] + TAC*verAC[1] + tad*verAD[1] + p
print('EQY : ',EQY)
EQZ = tab*verAB[2] + TAC*verAC[2] + tad*verAD[2]
print('EQZ : ',EQZ)
sol = solve({EQX,EQY,EQZ},{tab, tad, p})

TAB = float(sol[tab]); print('TAB = ','{:.1f}'.format(TAB),' N')
TAD = float(sol[tad]); print('TAD = ','{:.1f}'.format(TAD),' N')
P = float(sol[p]);     print('  P = ','{:.1f}'.format(P),' N')

EQX :  -0.470588235294118*tab + 0.384615384615385*tad + 36.0
EQY :  p - 0.705882352941177*tab - 0.738461538461539*tad - 38.4
EQZ :  0.529411764705882*tab - 0.553846153846154*tad + 28.8
TAB =  544.0  N
TAD =  572.0  N
  P =  844.8  N


### Apêndice

**Categorias de equações de equilíbrio no plano (3D)**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/GFormulas/EQ3D1.jpg"
style="max-width: 100%;"/>

Considere um objeto submetido a $n$ forças arbitrárias no espaço: $\vec{F}_1, \vec{F}_2, \ldots, \vec{F}_n$. O equilíbrio, de acordo com a segundas lei de Newton, expressa-se por:

\begin{equation*}
\sum_{i=1}^n\vec{F} = \vec{F}_1 + \vec{F}_2 + \ldots + \vec{F}_n = \vec{0}
\end{equation*}

Para desenvolver algebricamente esta expressão vetorial do equilíbrio de uma partícula, é conveniente expressar as quantidades vetoriais (com ponto de aplicação, direção, sentido e magnitude) por:

\begin{equation*}
\vec{F}_m = F_m \vec{\lambda}_m
\quad\quad  (m = 1, 2, \ldots, n)
\end{equation*}

em que $F_m$ é um escalar que representa a magnitude do vetor no espaço, enquanto que $\vec{\lambda}_m$ representa um vetor unitário (versor) - i.e . com normal igual a um - que define o ponto de aplicação, direção e sentido do vetor $\vec{F}_m$. Por uma questão de simplicidade e sem perda de generalidade, considere-se a seguir a notação: $\vec{F}_m \equiv \vec{F}$ e
$\vec{\lambda}_m \equiv \vec{\lambda}$.

Rene Descartes (1596-1650) foi o matemático francês que introduziu o sistema de coordenadas cartesiano (aparentemente uma ideia que lhe ocorreu para descrever a posição no espaço de uma mosca). Neste, a posição de uma partícula no espaço pode ser completamente definida à custa de três coordenadas, expressas num referencial $S(0,x,y,z)$ arbitrariamente escolhido.

Como é possível escrever o versor $\vec{\lambda}$ num sistema de coordenadas cartesiano e ortonormado? A adição de vetores no espaço pode ser expressa pela seguinte combinação linear (de vetores e escalares):

\begin{equation*}
\vec{\lambda} = \lambda_{x} \vec{\imath} +
\lambda_{y} \vec{\jmath} + \lambda_{z} \vec{k}
%\quad\quad  (i = 1, 2, \ldots, n)
\end{equation*}

em que $\lambda_{x}, \lambda_{y}, \lambda_{z}$ são escalares e $\vec{\imath}, \vec{\jmath}, \vec{k}$ são, por sua vez, os versores que definem, respetivamente, os eixos $x, y,z$ do sistema de coordenadas cartesiano. Como expressar os escalares $\lambda_{x}, \lambda_{y}, \lambda_{z}$? O que é que estes representam? Geometricamente, esta quantidades expressam a projeção do versor $\vec{\lambda}$ em cada um dos eixos coordenados, $\vec{\imath}, \vec{\jmath}, \vec{k}$. A projeção entre vetores é a interpretação geométrica do produto escalares entre dois vetores, pelo que:

\begin{equation*}
\begin{aligned}
\lambda_{x} = \vec{\lambda} \cdot \vec{\imath} &= || \vec{\lambda} ||.
||\vec{\imath}|| \cos
(\vec{\lambda},
\vec{\imath}) \equiv \cos\theta_x
%\quad\quad  (i = 1, 2, \ldots, n)
\\
\lambda_{y} = \vec{\lambda} \cdot \vec{\jmath} &= \cos\theta_y\\
\lambda_{z} = \vec{\lambda} \cdot \vec{k} &= \cos\theta_z\\
\end{aligned}
\end{equation*}

Chama-se cossenos diretores aos cosenos dos ângulos formados entre dois vetores coplanares.

O vetor força pode ser assim expresso a partir das suas componentes cartesianas num determinado sistema de coordenadas:

\begin{equation*}
\begin{aligned}
\vec{F} & = F(\lambda_{x} \vec{\imath} +
\lambda_{y} \vec{\jmath} + \lambda_{z} \vec{k})
%\quad\quad  (i = 1, 2, \ldots, n)
\\
& = F\cos\theta_x\,\vec{\imath} +
F\cos\theta_y\,\vec{\jmath} +
F\cos\theta_z\,\vec{k} \\
& = F_{x}\,\vec{\imath} +
F_{y}\,\vec{\jmath} + F_{z}\,\vec{k}
\end{aligned}
\end{equation*}

De notar que os cosenos diretores não todos independentes entre si.
Da algebra de matrizes, para um vetor genérico, $\vec{a} \equiv a_i,~(i= 1,\ldots,m)$, a $p$-norma para
vetores é dada por:

\begin{equation*}
||\vec{a}||_p = \left( \sum_{i}^m|a_i|^p\right)^{1/p}
\end{equation*}

Para o caso particular de $p = 2$ a norma vetorial é designada por norma de Frobenius escrevendo-se:

\begin{equation*}
||\vec{a}||_2 = (|a_1|^2 + \cdots + |a_m|^2 )^{1/2}
\end{equation*}

Desta forma, se considerarmos o vetor $\vec{F}$ no sistema de coordenadas cartesiano, a sua norma $L^2$ é dada por:

\begin{equation*}
\begin{aligned}
&~||\vec{F}||^2 = F_x^2 + F_y^2 + F_z^2 \\
\Leftrightarrow &~\left(\frac{F_x}{||\vec{F}||}\right)² + \left(\frac{F_y^2}{||\vec{F}||}\right)² +
\left(\frac{F_z^2}{||\vec{F}||}\right)^2 = 1\\
\end{aligned}
\end{equation*}

e, considernado as relações trigonométricas,

\begin{equation*}
\begin{aligned}
\frac{F_x}{||\vec{F}||} &= \cos\theta_x~;
\quad
\frac{F_y}{||\vec{F}||} &= \cos\theta_y~;
\quad
\frac{F_z}{||\vec{F}||} &= \cos\theta_z
\end{aligned}
\end{equation*}

resulta, finalmente,

\begin{equation*}
\cos\theta_x^2 + \cos\theta_y^2 +
\cos\theta_z^2 = 1
\end{equation*}

Este mesmo resultado poderia ter sido concluido diretamnte pelo facto do vetor $\vec{\lambda}$ ter norma unitária (versor), pelo que a soma dos quadrados dos seus componentes deve ser igual ao quadrado da sua amplitude.

\begin{equation*}
\lambda_x^2 + \lambda_y^2 +
\lambda_z^2 = 1
\end{equation*}

---

Copyright (c) DEMI - FCT NOVA

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>