<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/iLogos/logo_novafct.png" width="200">

# Departamento de Engenharia Mecânica e Industrial
## Mecânica Aplicada I 


## EQUILÍBRIO DO CORPO RÍGIDO NO ESPAÇO

### Problema 2

A placa rectangular da figura tem uma massa de 100 kg e é mantida na posição indicada na figura por duas dobradiças A e B e por um cabo DCE que passa por uma roldana em C. Supondo que a força de tração é a mesma em ambos os troços do cabo e que a dobradiça em B não exerce reacção na direção do seu eixo, determine:

**a)** A força de tração no cabo.

**b)** As reações em A e B.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch04/P2/MAI_Ch04_P2.png"
width="500">


### Resolução

#### **a)** A força de tração no cabo.

##### Diagrama de corpo livre

Comece-se por elaborar o diagrama de corpo livre da placa, identificando sobre esta todas as forças externas aplicadas. Além do peso próprio (na direção da força gravitacional que se assume segundo o eixo coordenado $y$), existem as forças de reação nas dobradiças em A e B e as forças exercidas pelo cabo na roldana em C:

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch04/P2/MAI_Ch04_P2a.jpg"
width="500">

Identificam-se as incógnitas do problema:

1. No apoio $A$ : $R_{Ax}$, $R_{Ay}$ e $R_{Az}$ (reacções no apoio);

2. No apoio $B$ : $R_{By}$ e $R_{By}$ (reacções no apoio);

3. No Ponto $C$ : $T_{CD}$ e $T_{CE}$. (forças de tracção no cabo DCE). De notar que, como se trata do mesmo cabo verifica-se, por hipótese: $T_{CD} = T_{CE} = T$.

Desta forma, resulta o seguinte balanço em termos das componentes cartesianas das forças envolvidas no DCL:

* Forças incógnitas : $R_\textrm{Ax}, R_\textrm{Ay}, R_\textrm{Az},
R_\textrm{Bx}, R_\textrm{Bz}, T$;

* Força conhecida : $P$.

Como do equilíbrio do corpo rígido conduz a 6 equações, convenientemente, existem 6 incógnitas.

#### Equilíbrio estático

A condição de equilíbrio de um sólido rígido no espaço pressupõe:

\begin{equation*}
\bullet\quad\sum \vec{F} = \vec{0}~\Leftrightarrow~
\begin{cases}
\rightarrow(+)&x:&\sum F_x = 0 \\
\uparrow(+)&y:&\sum F_y = 0 \\
\swarrow(+)&z:&\sum F_z = 0 \\
\end{cases}
\end{equation*}

e

\begin{equation*}
\bullet\quad\sum \vec{M}_A = \vec{0}~\Leftrightarrow~
\begin{cases}
\vec{k}\times\vec{\jmath} = \vec{\imath}~(+)&:&\sum M_{Ax} = 0 \\
\vec{k}\times\vec{\imath} = \vec{\jmath}~(+)&:&\sum M_{Ay} = 0 \\
\vec{\imath}\times\vec{\jmath} = \vec{k}~(+)&:&\sum M_{Az} = 0 \\
\end{cases}
\end{equation*}

De notar que o ponto genérico A ($\sum \vec{M}_A$) que representa o polo sobre o qual é calculado o momento das forças aplicadas, deve ser criteriosamente ou convenientemente escolhido.

Para desenvolver e resolver as equações de equilíbrio torna-se necessários, antes de mais, expressar no sistema de coordenadas escolhido, os vetores das forças identificadas no diagrama de corpo livre:

\begin{equation*}
\begin{cases}
\vec{R}_\textrm{A} = R_\textrm{Ax}\vec{\imath} + R_\textrm{Ay}\vec{\jmath}
+ R_\textrm{Az}\vec{z}  \\
\vec{R}_\textrm{B} = 0\vec{\imath} + R_\textrm{By}\vec{\jmath}
+ R_\textrm{Bz}\vec{z}  \\
\vec{T}_\textrm{CD} = T_\textrm{CD}\vec{\lambda}_\textrm{CD} \\
\vec{T}_\textrm{CE} = T_\textrm{CE}\vec{\lambda}_\textrm{CE} \\
\vec{P} = -P\, \vec{\jmath}
\end{cases}
\end{equation*}

os versores $\vec{\lambda}$ definem a direção e sentido onde atuam as forças de tração no cabo DCE. As componentes cartesianas dos $\vec{\lambda}$ são os cossenos diretores, definidos pelos ângulos formados entre a linha de ação da (direção) da força e os eixos coordenados ($\vec{\imath},\vec{\jmath},\vec{k}$). Na prática estes vetores unitários serão obtidos a partir de vetores geométricos que partilham a mesma direçaão do vetor força de tração nos cabos:

\begin{equation*}
\vec{\lambda}_\textrm{CD}
= \displaystyle\frac{\vec{T}_\textrm{CD}}{T_\textrm{CD}}
= \displaystyle\frac{\vec{CD}}{||\vec{CD}||}
\quad\wedge\quad
\vec{\lambda}_\textrm{CE}
= \displaystyle\frac{\vec{T}_\textrm{CE}}{T_\textrm{CE}}
= \displaystyle\frac{\vec{AC}}{||\vec{AC}||}
\end{equation*}

#### Coordenadas de pontos geométricos do problema

\begin{equation*}
\begin{aligned}
&A(90,0,0)~;~
B(870,0,0)~;~
C(690,0,450)\\
&D(0,675,0)~;~
E(960,675,0)~;~
G(480,0,225)
\end{aligned}
\end{equation*}

In [11]:
import numpy as np

A = [90,0,0] # unit: mm
B = [870,0,0]
C = [690,0,450]
D = [0,675,0]
E = [960,675,0]
G = [480,0,225]

#### Vetores - componentes cartesianos e módulos:

* $\vec{CD}$:

\begin{equation*}
\vec{CD} = \vec{OD} - \vec{OC} = (0,675,0) - (690,0,450) = -690\vec{\imath} +675
\vec{\jmath} -450\vec{k}\\
\end{equation*}

In [12]:
vCD = np.subtract(D,C); print('vCD = ',vCD)

vCD =  [-690  675 -450]


\begin{equation*}
||\vec{CD}|| = \sqrt{CD_x^2+CD_y^2+CD_z^2}
= \sqrt{(-690)^2+ 675^2 +(-450)^2} = 1065.0~\textrm{mm}\\
\end{equation*}

In [13]:
modCD = np.sqrt(np.dot(vCD,vCD))
print('modulo de CD = ','{:.1f}'.format(modCD),' mm')

modulo de CD =  1065.0  mm


* $\vec{CE}$:

\begin{equation*}
\vec{CE} = \vec{OE} - \vec{OC} = (960,675,0) - (690,0,450)
= 270\vec{\imath} + 675 \vec{\jmath} -450\vec{k}\\
\end{equation*}

In [14]:
vCE = np.subtract(E,C); print('vCE = ',vCE)

vCE =  [ 270  675 -450]


\begin{equation*}
|| \vec{CE}|| = \sqrt{CE_x^2+CE_y^2+CE_z^2}
= \sqrt{(270)^2+ 675^2 +(-450)^2} = 855.0~\textrm{mm}\\
\end{equation*}

In [15]:
modCE = np.sqrt(np.dot(vCE,vCE))
print('modulo de CE = ','{:.1f}'.format(modCE),' mm')

modulo de CE =  855.0  mm


Assim sendo os vetores das forças aplicadas em C vêm:

\begin{equation*}
\begin{aligned}
\bullet~\vec{T}_\textrm{CD} = T_\textrm{CD}\vec{\lambda}_\textrm{CD}
= T_\textrm{CD}\frac{\vec{CD}}{||\vec{CD}||} =
T_\textrm{CD}(-0.648 \vec{\imath} +0.634 \vec{\jmath} -0.423 \vec{k})
\end{aligned}
\end{equation*}

In [16]:
np.set_printoptions(precision=3)
verCD = vCD/modCD
print('verCD = ',verCD)
print('Verifications: ----------')
print('norma verCD:',np.sqrt(np.dot(verCD,verCD)))

verCD =  [-0.648  0.634 -0.423]
Verifications: ----------
norma verCD: 1.0


\begin{equation*}
\begin{aligned}
\bullet~\vec{T}_\textrm{CE} = T_\textrm{CE}\vec{\lambda}_\textrm{CE}
= T_\textrm{CE}\frac{\vec{CE}}{||\vec{CE}||} =
T_\textrm{CE}(0.316 \vec{\imath} + 0.789 \vec{\jmath} -0.526 \vec{k})
\end{aligned}
\end{equation*}

In [17]:
np.set_printoptions(precision=3)
verCE = vCE/modCE
print('verCE = ',verCE)
print('Verifications: ----------')
print('norma verCE:',np.sqrt(np.dot(verCE,verCE)))

verCE =  [ 0.316  0.789 -0.526]
Verifications: ----------
norma verCE: 1.0


#### Roldana: força resultante aplicada em C

Cmo a força de tração no cabo toma o mesmo valor ($T_{CE} = T_{CD} = T$), os vetores relativos às forças de tração no cabo DCE podem simplesmsente reescrever-se, por simplicidade, por uma força resultante aplicada em C:

\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{C} &= \vec{T}_\textrm{CE} + \vec{T}_\textrm{CD} \\
&= T_\textrm{CD}(-0.648 \vec{\imath} +0.634 \vec{\jmath} -0.423 \vec{k})
+ T_\textrm{CE}(0.316 \vec{\imath} + 0.789 \vec{\jmath} -0.526
\vec{k}) \\
&=T(-0.332\vec{\imath} + 1.423 \vec{\jmath} -0.949\vec{k})
\end{aligned}
\end{equation*}

In [18]:
verTC = (verCD+verCE); print('ver TC = ', verTC)

ver TC =  [-0.332  1.423 -0.949]


#### Desenvolvendo as equações escalares do equilíbrio das forças

\begin{equation*}
\bullet
\begin{cases}
\sum F_x = 0 \\
\sum F_y = 0 \\
\sum F_z = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
R_\textrm{Ax} -0.332\,T = 0 \\
R_\textrm{Ay} + R_\textrm{By} +1.423\,T - P = 0 \\
R_\textrm{Az} + R_\textrm{Bz} -0.949\,T = 0 \\
\end{cases}
\end{equation*}

#### Desenvolvendo as equações escalares do equilíbrio dos momentos das forças

Do equilíbrio estático sabe-se que, se um corpo for submetido a um sistema de forças, o momento resultante dessas forças em relação a um ponto A, pode ser determinado pela adição dos vetores momento de cada força:

\begin{equation*}
\begin{aligned}
\bullet\quad&\left(\vec{M}_R\right)_A =
\sum_i \vec{r}_{Ai}\times\vec{F_i} = \vec{0} \\
~\Leftrightarrow~&
(\vec{r}_{\textrm{AG}}\times\vec{P}) +
(\vec{r}_{\textrm{AC}}\times\vec{T}_\textrm{C}) +
(\vec{r}_{\textrm{AB}}\times\vec{R}_\textrm{B}) = \vec{0}
\end{aligned}
\end{equation*}

Os vetores posição entre o polo A e os pontos de aplicação das forças que produzem momento em relação a esse polo têm as seguintes componentes cartesianas:

\begin{equation*}
\begin{aligned}
\vec{r}_{\textrm{AG}} = \vec{OG} - \vec{OA} = 390&\vec{\imath}~+~0\vec{\jmath} +~225\,
\vec{k} \\
\vec{r}_{\textrm{AC}} = \vec{OC} - \vec{OA} = 600&\vec{\imath}~+~0\vec{\jmath} +~450\,
\vec{k} \\
\vec{r}_{\textrm{AB}} = \vec{OB} - \vec{OA} = 780&\vec{\imath}~+~0\vec{\jmath} +~0\,
\vec{k} \\
\end{aligned}
\end{equation*}

In [19]:
rAG =  np.subtract(G,A); print('rAG = ',rAG)
rAC =  np.subtract(C,A); print('rAC = ',rAC)
rAB =  np.subtract(B,A); print('rAB = ',rAB)

rAG =  [390   0 225]
rAC =  [600   0 450]
rAB =  [780   0   0]


O cálculo do produto vetorial entre vetores pode ser calculado pelo determinante de uma matriz de acordo com o seguinte formulário:

\begin{equation*}
(\vec{r}_{\textrm{AG}}\times\vec{P}) +
(\vec{r}_{\textrm{AC}}\times\vec{T}_\textrm{C}) +
(\vec{r}_{\textrm{AB}}\times\vec{R}_\textrm{B}) = \vec{0}
\end{equation*}

\begin{equation*}
~\Leftrightarrow~
\begin{vmatrix}
\vec{\imath} & \vec{\jmath} & \vec{k} \\
x_{\textrm{AG}} & 0 & z_{\textrm{AG}} \\
0 & -P & 0
\end{vmatrix}+
\begin{vmatrix}
\vec{\imath} & \vec{\jmath} & \vec{k} \\
x_{\textrm{AC}} & 0 & z_{\textrm{AC}} \\
-0.332\,T & 1.423\,T & -0.949\,T
\end{vmatrix}
+
\begin{vmatrix}
\vec{\imath} & \vec{\jmath} & \vec{k} \\
x_{\textrm{AB}} & 0 & 0 \\
0 & R_\textrm{By} & R_\textrm{Bz}
\end{vmatrix} = \vec{0}
\end{equation*}

\begin{equation*}
~\Leftrightarrow~
\begin{vmatrix}
\vec{\imath} & \vec{\jmath} & \vec{k} \\
x_{\textrm{AG}} & 0 & z_{\textrm{AG}} \\
0 & -P & 0
\end{vmatrix}+
\begin{vmatrix}
\vec{\imath} & \vec{\jmath} & \vec{k} \\
x_{\textrm{AC}} & 0 & z_{\textrm{AC}} \\
-0.332\,T & 1.423\,T & -0.949\,T
\end{vmatrix}
+
\begin{vmatrix}
\vec{\imath} & \vec{\jmath} & \vec{k} \\
x_{\textrm{AB}} & 0 & 0 \\
0 & R_\textrm{By} & R_\textrm{Bz}
\end{vmatrix} = \vec{0}
\end{equation*}

\begin{equation*}
\begin{aligned}
~\Leftrightarrow~&
(225000\,\vec{\imath} - 390000\,\vec{k} ) +
T(-640.47\,\vec{\imath}  + 419.87 \,\vec{\jmath} + 853.97\,\vec{k}) +
(- 780\,R_\textrm{Bz}\,\vec{\jmath} + 780\,R_\textrm{By}\,\vec{k}) =
\vec{0}\\
~\Leftrightarrow~&
(225000-640.47\,T) \,\vec{\imath}
+ (419.87\,T - 780\,R_\textrm{Bz})\,\vec{\jmath}
+ (853.97\,T + 780\,R_\textrm{By} - 390000 )
\,\vec{k} = \vec{0}
\end{aligned}
\end{equation*}

Decompondo estas quantidades vetoriais nas equações escalares do equilíbrio dos momentos produzidos pelas forças externas aplicadas resulta o seguinte sistema de equações:

\begin{equation*}
\bullet\quad\sum \vec{M}_A = \vec{0}~\Leftrightarrow~
\begin{cases}
\sum M_{Ax} = 0 \\
\sum M_{Ay} = 0 \\
\sum M_{Az} = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
225000 - 640.47\,T = 0 \\
419.87\,T - 780R_\textrm{Bz}= 0 \\
- 390000 + 853.97\,T + 780R_\textrm{By} = 0
\end{cases}
\end{equation*}

In [20]:
import sympy as sy
from sympy.solvers import solve
from sympy.physics.mechanics import ReferenceFrame, cross

S = ReferenceFrame('S') # ||x|| = ||y|| = ||z|| = 1
t, rax, ray, raz, rby, rbz = sy.symbols('t rax ray raz rby rbz')

m = 100 # unit:kg
g = 10 # unit: m/s^2
P = m*g; print('P = ',P,' N')
vAG = rAG[0]*S.x + rAG[1]*S.y + rAG[2]*S.z
vAC = rAC[0]*S.x + rAC[1]*S.y + rAC[2]*S.z
vAB = rAB[0]*S.x + rAB[1]*S.y + rAB[2]*S.z
vP = -P*S.y
vTC = t*(verTC[0]*S.x + verTC[1]*S.y + verTC[2]*S.z)
vRB = rby*S.y + rbz*S.z

CP1 = cross(vAG,vP); print('Cross 1: ',CP1)
CP2 = cross(vAC,vTC); print('Cross 2: ',CP2)
CP3 = cross(vAB,vRB); print('Cross 3: ',CP3)
expMA = CP1 + CP2 + CP3
print('Exp MA = ',expMA)

P =  1000  N
Cross 1:  225000*S.x - 390000*S.z
Cross 2:  - 640.474425500371*t*S.x + 419.866567828021*t*S.y + 853.965900667161*t*S.z
Cross 3:  - 780*rbz*S.y + 780*rby*S.z
Exp MA =  (225000 - 640.474425500371*t)*S.x + (-780*rbz + 419.866567828021*t)*S.y + (780*rby + 853.965900667161*t - 390000)*S.z


Agrupando o seguinte sistema de equações (6 equações a 6 incógnitas):

\begin{equation*}
\bullet\quad
\begin{cases}
\sum F_x = 0 \\
\sum F_y = 0 \\
\sum F_z = 0 \\
\sum M_{Ax} = 0 \\
\sum M_{Ay} = 0 \\
\sum M_{Az} = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
R_\textrm{Ax} -0.332\,T = 0 \\
R_\textrm{Ay} + R_\textrm{By} +1.423\,T - P = 0 \\
R_\textrm{Az} + R_\textrm{Bz} -0.949\,T = 0 \\
225000 - 640.47\,T = 0 \\
419.87\,T - 780R_\textrm{Bz}= 0 \\
- 390000 + 853.97\,T + 780R_\textrm{By} = 0
\end{cases}
\end{equation*}

A implementação da solução do sistema de equações à luz da alebra linear vem:

In [24]:
EFX = t*verTC[0] + rax
EFY = t*verTC[1] + ray + rby - P
EFZ = t*verTC[2] + raz + rbz
EMX = expMA.args[0][0].args[2][0]
EMY = expMA.args[0][0].args[2][1]
EMZ = expMA.args[0][0].args[2][2]

sol = solve({EFX,EFY,EFZ,EMX,EMY,EMZ},{t, rax, ray, raz, rby, rbz})

T   = float(sol[t]);  print('  T = ','{:.1f}'.format(T),' N')
RAx = float(sol[rax]); print('RAx = ','{:.1f}'.format(RAx),' N')
RAy = float(sol[ray]); print('RAy = ','{:.1f}'.format(RAy),' N')
RAz = float(sol[raz]); print('RAz = ','{:.1f}'.format(RAz),' N')
RBy = float(sol[rby]); print('RBy = ','{:.1f}'.format(RBy),' N')
RBz = float(sol[rbz]); print('RBz = ','{:.1f}'.format(RBz),' N')

  T =  351.3  N
RAx =  116.7  N
RAy =  384.6  N
RAz =  144.2  N
RBy =  115.4  N
RBz =  189.1  N


O sistema de equações anterior é equivalente a uma equação matricial da forma:

\begin{equation*}
[A]\{x\} = \{b\}
\Leftrightarrow
\begin{bmatrix}
% RAx RAz MAx MAz TCF TDE
-0.332 & 1 & 0 & 0 & 0 & 0 \\
1.423 & 0 & 1 & 0 & 1 & 0 \\
-0.949 & 0 & 0 & 1 & 0 & 1 \\
640.47 & 0 & 0 & 0 & 0 & 0 \\
419.87 & 0 & 0 & 0 & 0 & -780 \\
853.97 & 0 & 0 & 0 & 780 & 0
\end{bmatrix}
\begin{Bmatrix}
T \\
R_\textrm{Ax} \\
R_\textrm{Ay} \\
R_\textrm{Az} \\
R_\textrm{By} \\
R_\textrm{Bz}
\end{Bmatrix} =
\begin{Bmatrix}
0 \\
1000 \\
0 \\
225000 \\
0 \\
390000
\end{Bmatrix}
\end{equation*}

Cuja solução é obtida multiplicando, ambos os membros, à esquerda por $[A]^{-1}$:

\begin{equation*}
\begin{Bmatrix}
T \\
R_\textrm{Ax} \\
R_\textrm{Ay} \\
R_\textrm{Az} \\
R_\textrm{By} \\
R_\textrm{Bz}
\end{Bmatrix}
= [A]^{-1}~\{b\}
\end{equation*}

In [22]:
np. set_printoptions(precision=1, suppress=True)

A1 = [-0.332,1,0,0,0,0]
A2 = [1.423, 0, 1, 0, 1, 0]
A3 = [-0.949, 0, 0, 1, 0, 1]
A4 = [640.47, 0, 0, 0, 0, 0]
A5 = [419.87, 0, 0, 0, 0, -780]
A6 = [853.97, 0, 0, 0, 780, 0]

A = np.array([A1,A2,A3,A4,A5,A6])
print(f'A =\n {A}')

invA = np.linalg.inv(A)
print(f'A^-1 =\n {invA}')

b = np.array([0,P,0,225000,0,390000])
print(f'b = {b}')

x = np.linalg.solve(A,b)
print(f'x = {x} [N / N.mm]')

A =
 [[  -0.3    1.     0.     0.     0.     0. ]
 [   1.4    0.     1.     0.     1.     0. ]
 [  -0.9    0.     0.     1.     0.     1. ]
 [ 640.5    0.     0.     0.     0.     0. ]
 [ 419.9    0.     0.     0.     0.  -780. ]
 [ 854.     0.     0.     0.   780.     0. ]]
A^-1 =
 [[ 0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0. -0.  0. -0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-0. -0. -0. -0. -0.  0.]
 [-0. -0. -0.  0. -0. -0.]]
b = [     0   1000      0 225000      0 390000]
x = [351.3 116.6 384.7 144.3 115.4 189.1] [N / N.mm]


<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch04/P2/MAI_Ch04_P2b.jpg"
width="700">

#### Momento de forças sobre um eixo

Supondo que só se pretendia determinar a força de tração no cabo DCE, poder-se-ia recorrer a uma resolução alternativa, pela análise vetorial do momento produzido pelas forças sobre um eixo específico.

Escolha-se o eixo AB ou eixo coordenado $x$. Excluam-se todas as forças que concorram para qualquer ponto pertencente a esse eixo. Para o problema em análise, exclui-se as forças de reação em A ($R_{Ax}, R_{Ay}, R_{Az}$) e B ($R_{By}, R_{Bz}$). Estas forças não se consideram porque se anulam no cálculo vetorial do produto escalar, a seguir definido. Comece-se por escolher um ponto arbitrário no eixo AB; por conveniência escolha-se o ponto A.

Para calcular o momento das forças em relação ao eixo $x$ usando a análise vetorial: (i) determina-se o momento resultante das forças em relação a um ponto arbitrário do eixo (ponto A, neste caso); (ii) desenvolve-se o produto escalar no vetor momento resultante e o versor desse eixo coordenado:

\begin{equation*}
\begin{aligned}
M_{\textrm{eixo AB}} \equiv \sum\vec{M}_{\vec{\imath}}
&= \vec{\imath} \cdot
\sum_{n=1}^3\vec{M}_A^{\vec{F}_n} = \vec{0} \\
~\Leftrightarrow~&
\vec{\imath} \cdot
\left(\vec{r}_{\textrm{AC}}\times\vec{P} +
\vec{r}_{\textrm{AC}}\times\vec{T}_\textrm{CE} +
\vec{r}_{\textrm{AC}}\times\vec{T}_\textrm{CD}\right) = \vec{0} \\
~\Leftrightarrow~&
\vec{\imath} \cdot
\left(\vec{r}_{\textrm{AC}}\times\vec{P} +
\vec{r}_{\textrm{AC}}\times\vec{T}\right) = \vec{0}
\end{aligned}
\end{equation*}

em que,

\begin{equation*}
\begin{aligned}
\vec{r}_\textrm{AC} &= 600\vec{\imath}~+~0\vec{\jmath} +~450\,\vec{k} \\
\vec{T} &= \vec{T}_\textrm{CE} + \vec{T}_\textrm{CD} =T(-0.332\vec{\imath} +
1.423 \vec{\jmath} -0.949\vec{k})\\
\vec{P} &= -P\, \vec{\jmath}\\
\end{aligned}
\end{equation*}

In [23]:
from sympy.physics.mechanics import dot

eixoAB = 1*S.x + 0*S.y + 0*S.z
print('eixo AB : ',eixoAB)
crossAB = cross(vAC,vTC) + cross(vAG,-P*S.y)
print('Cross product A : ')
print('               i : ',crossAB.args[0][0][0])
print('               j : ',crossAB.args[0][0][1])
print('               k : ',crossAB.args[0][0][2])
EQi = dot(eixoAB,crossAB)
print('Dot Product = ',EQi)
sol = solve({EQi},{t})

T2   = float(sol[t]);  print('  T = ','{:.1f}'.format(T2),' N')

eixo AB :  S.x
Cross product A : 
               i :  225000 - 640.474425500371*t
               j :  419.866567828021*t
               k :  853.965900667161*t - 390000
Dot Product =  225000 - 640.474425500371*t
  T =  351.3  N


Como nota final, salienta-se que esta última abordagem, pela mecânica vetorial da resultante dos momentos de forças em relação a um eixo, pode ser sobretudo útil na análise de forças aplicadas a estruturas hiperestáticas (sobre as quais não é possível, portanto, calcular todas as incógnitas do problema apenas pela análise das equações de equilíbrio - para tal outros métodos de mecânica das estruturas são necessários, como o método das forças ou o método dos deslocamentos). Neste caso, o eixo a considerar deve ser tal que elimine da equação algumas forças incógnitas do problema, permitindo assim determinar parte das forças desconhecidas do sistema.


## Apêndice A

Qualquer sistema de forças, $F_1, F_2, \ldots, F_n$ pode ser substituído por um sistema força-binário equivalente aplicado num dado ponto $O$, constituído pelos vetores $\vec{R}$ e $M_0^R$. Quando as forças que actuam sobre um corpo podem ser reduzidas, num ponto arbitrário $O$, a um sistema força-binário constituído por uma força nula e um binário nulo, diz-se que o corpo está em equilíbrio estático.

As condições necessárias e suficientes para garantir o equilíbrio são:

\begin{equation*}
\begin{cases}
\sum\vec{F} = \vec{0}\\
\sum\vec{M}_0 = \sum\vec{r}\times\vec{F} = \vec{0}
\end{cases}
\end{equation*}

Decompondo a força e o momento nas suas componentes cartesianas, estas duas equações vectoriais conduzem às seguintes seis equações escalares:

\begin{equation*}
\begin{cases}
~\sum F_x = 0\\
~\sum F_y = 0\\
~\sum F_z = 0\\
\sum M_x = 0 \\
\sum M_y = 0 \\
\sum M_z = 0
\end{cases}
\end{equation*}

Para escrever as equações de equilíbrio de um corpo rígido é essencial identificar todas as forças aplicadas no corpo.  Essas forças devem constar do diagrama de corpo livre.

**Resolvendo a forma determinante do produto vetorial $\vec{A}\times\vec{B}$**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/GFormulas/CrossProd.jpg"
width="700">

**Categorias de equações de equilíbrio no plano (3D)**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/GFormulas/EQ3D.jpg"
width="700">

**Reações nos apoios em três dimensões**

As reações sobre um corpo rígido estrutural tridimensional podem ir desde uma única força de direção e sentido desconhecida exercida por uma superfície lisa, a um sistema força-binário, exercido por um encastramento. Pelo que o número de incognitas aasocidas a uma reação pode varia de um a seis nos problemas que envolvem o equilíbrio estático geral. A figura infra sumaria vários tipos de ligações e correspondentes reações. Uma força simples de determinar o tipo de reação e consequentemente o número de incógnitas envolvidas, é verificar quais dos seis graus de liberdade (movimentos fundamentais de translação nas direções $x$, $y$ e $z$ e rotação em torno dos eixos $x$, $y$ e $z$) são permitidos e quais os impedidos.

É de notar que alguns apoios (e.g. dobradiças, chumaceira) possuem reações em termos de forças e momentos. No entanto quando estes apoios são usados conjuntamente no corpo rígido com outros apoios iguais, devidamente alinhados, então as forças de reação destes apoios, sozinhas, são suficientes para manter o corpo em equilíbrio. Ou seja, os momentos tornam-se redundantes e devem, por isso, ser omitidos do diagrama de corpo livre, possibilitando a resolução do problema com a análise das equações de equilíbrio.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/GFormulas/ReacoesApoios3D.jpg"
width="700">

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/GFormulas/TabReac2.png"
width="700">

## Apêndice B

Genericamente, uma dobradiça pode exercer sobre um corpo quer forças de reação quer momentos de reação. De notar que o momento na reação será sempre perpendicular ao eixo $a-a$ da dobradiça, pois a rotação sobre este eixo é livre. Contudo, a dobradiça nunca é projetada para absorver momentos. Tipicamente as dobradiças são colodas aos pares para eliminar esse moemnto de reação. Consequentemente, o modelo matemático despreza as reações de momento, considerando apenas forças de reação.


<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch04/P2/AppB.png" width="300">

---

Copyright (c) DEMI - FCT NOVA

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>