<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/iLogos/logo_novafct.png" width="200">

# Departamento de Engenharia Mecânica e Industrial
## Mecânica Aplicada I 

## EQUILÍBRIO DA PARTÍCULA NO ESPAÇO

### Problema 10

Um recipiente de peso $\vec{P}$ está suspenso em A, ao qual os cabos AC e AE estão
ligados. Uma força $\vec{Q}$ está aplicada à extremidade F de um terceiro cabo FBAD que
passa em roldanas nos pontos A e B. Sabendo que $P = 1000$ N, determine a
intensidade de $Q$. Considere que a força de tração no cabo FBAD é constante em
todos os troços.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch02/P10/MAI_Ch02_P10.png"
style="width: 20%; max-width: 100%;"/>

#### Resumo

Objectivos de aprendizaem:

- Conseguir determinar as componentes cartesianas de uma força no espaço.

- Conseguir estabelecer as equações de equilíbrio de uma partícula no espaço.

### Resolução

**(a)** Considere-se a partícula no ponto A. Sobre esta partícula atuam as seguintes forças externas:

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch02/P10/MAI_Ch02_P10a.jpg"
style="width: 20%; max-width: 100%;"/>

Pelo enunciado verifica-se:

\begin{equation}
||\vec{T}_\textrm{AB} || = ||\vec{T}_\textrm{AD} || = ||\vec{Q} ||
\end{equation}

A condição de equilíbrio da partícula do espaço pressupõe:

\begin{equation}
\sum \vec{F} = \vec{0}\Leftrightarrow
\vec{T}_\textrm{AB} + \vec{T}_\textrm{AC}
+ \vec{T}_\textrm{AD} + \vec{T}_\textrm{AE} + \vec{P} =
\vec{0}
\end{equation}

Torna-se necessário escrever estas quantidades vetoriais pelas suas componentes cartesianas no referencial cartesiano escolhido. Assim sendo, a equação vetorial de equilíbrio pode ser decomposta em três equações esclares de acordo com as componentes dos vetores segundo os eixos do referencial cartesiano escolhido:

\begin{equation*}
\begin{cases}
\sum F_x = 0\\
\sum F_y = 0\\
\sum F_z = 0
\end{cases}
\end{equation*}

Decompondo os vetores de força aplicadas vêm:

\begin{equation*}
\begin{cases}
\vec{T}_\textrm{AB} = T_\textrm{AB}\vec{\lambda}_\textrm{AB}
= T_\textrm{AB}\frac{\vec{AB}}{||\vec{AB}||} \\
\vec{T}_\textrm{AC} = T_\textrm{AC}\vec{\lambda}_\textrm{AC}
= T_\textrm{AB}\frac{\vec{AC}}{||\vec{AC}||} \\
\vec{T}_\textrm{AD} = T_\textrm{AD}\vec{\lambda}_\textrm{AD}
= T_\textrm{AD}\frac{\vec{AD}}{||\vec{AD}||} \\
\vec{T}_\textrm{AE} = T_\textrm{AE}\vec{\lambda}_\textrm{AE}
= T_\textrm{AE}\frac{\vec{AE}}{||\vec{AE}||} \\
\vec{P} = -P \vec{\jmath}
\end{cases}
\end{equation*}

em que os versores $\vec{\lambda}$ definem a direção e sentido onde atuam as
respetivas forças. Assim sendo, é necessário conhecer os cossenos diretores
associados a estes versores em relação ao sistema de coordenadas escolhido
$S(0,\vec{\imath},\vec{\jmath},\vec{k})$. Têm-se:

- Pontos:

\begin{equation*}
\begin{aligned}
&A~\mapsto~(0,-1.6,0)\\
&B~\mapsto~(-0.78,0,0)\\
&C~\mapsto~(0,0,1.2)\\
&D~\mapsto~(1.3,0,0.4)\\
&E~\mapsto~(-0.4,0,-0.86)\\
\end{aligned}
\end{equation*}

In [1]:
import numpy as np

A = [0,-1.6,0] # unit: m
B = [-0.78,0,0]
C = [0,0,1.2]
D = [1.3,0,0.4]
E = [-0.4,0,-0.86]

- Vetores - componentes cartesianos:

\begin{equation*}
\vec{AB} = B - A = (-0.78,0,0) - (0,-1.6,0) = -320\vec{\imath} -480 \vec{\jmath} + 360
\vec{k}\\
\end{equation*}

In [2]:
vAB = np.subtract(B,A); print('vAB = ',vAB)


vAB =  [-0.78  1.6   0.  ]


\begin{equation*}
\vec{AC} = C - A = (0,0,1.2) - (0,-1.6,0) = 450\vec{\imath} -480 \vec{\jmath} + 360
\vec{k}\\
\end{equation*}

In [3]:
vAC = np.subtract(C,A); print('vAC = ',vAC)

vAC =  [0.  1.6 1.2]


\begin{equation*}
\vec{AD} = D - A = (1.3,0,0.4) - (0,-1.6,0) = 250\vec{\imath} -480
\vec{\jmath} - 360 \vec{k}\\
\end{equation*}

In [4]:
vAD = np.subtract(D,A); print('vAD = ',vAD)

vAD =  [1.3 1.6 0.4]


\begin{equation*}
\vec{AE} = E - A = (-0.4,0,-0.86) - (0,-1.6,0) = 250\vec{\imath} -480
\vec{\jmath} - 360 \vec{k}\\
\end{equation*}

In [5]:
vAE = np.subtract(E,A); print('vAE = ',vAE)

vAE =  [-0.4   1.6  -0.86]


- Vetores - módulos:

Por definição de norma de um vetor genérico $\vec{v}$:

\begin{equation*}
||\vec{v}|| = \sqrt{\vec{v}\cdot\vec{v}} =
\sqrt{v_x^2 + v_y^2 + v_z^2}\\
\end{equation*}

Pelo que,

\begin{equation*}
||\vec{AB}|| = \sqrt{(-0.78)^2+ 1.6^2 } = 1.78~\textrm{mm}\\
\end{equation*}

In [6]:
modAB = np.sqrt(np.dot(vAB,vAB))
print('modulo de AB = ','{:.2f}'.format(modAB),' mm')

modulo de AB =  1.78  mm


\begin{equation*}
||\vec{AC}|| = \sqrt{1.6^2+ 1.2^2} = 2.0~\textrm{mm}\\
\end{equation*}

In [7]:
modAC = np.sqrt(np.dot(vAC,vAC))
print('modulo de AC = ','{:.2f}'.format(modAC),' mm')


modulo de AC =  2.00  mm


\begin{equation*}
||\vec{AD}|| = \sqrt{1.3^2 + 1.6^2 + 0.4^2} = 2.1~\textrm{mm}\\
\end{equation*}

In [8]:
modAD = np.sqrt(np.dot(vAD,vAD))
print('modulo de AD = ','{:.2f}'.format(modAD),' mm')

modulo de AD =  2.10  mm


\begin{equation*}
||\vec{AE}|| = \sqrt{(-0.4)^2 + 1.6^2 +(-0.86)^2} = 1.86~\textrm{mm}\\
\end{equation*}

In [9]:
modAE = np.sqrt(np.dot(vAE,vAE))
print('modulo de AE = ','{:.2f}'.format(modAE),' mm')

modulo de AE =  1.86  mm


Assim sendo os vetores das forças aplicadas em A vêm:

\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AB} = T_\textrm{AB}\vec{\lambda}_\textrm{AB}
= Q\frac{\vec{AB}}{||\vec{AB}||} =
Q(-0.438\vec{\imath} + 0.899\vec{\jmath})
\end{aligned}
\end{equation*}

In [10]:
np.set_printoptions(precision=3)
verAB = vAB/modAB
print('verAB = ',verAB)


verAB =  [-0.438  0.899  0.   ]


\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AC} = T_\textrm{AC}\vec{\lambda}_\textrm{AC}
= T_\textrm{AC}\frac{\vec{AC}}{||\vec{AC}||} =
T_\textrm{AC}(0.8 \vec{\jmath} + 0.6\vec{k})
\end{aligned}
\end{equation*}

In [11]:
np.set_printoptions(precision=3)
verAC = vAC/modAC
print('verAC = ',verAC)


verAC =  [0.  0.8 0.6]


\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AD} = T_\textrm{AD}\vec{\lambda}_\textrm{AD}
= Q\frac{\vec{AD}}{||\vec{AD}||} =
Q (0.619\vec{\imath} + 0.762\vec{\jmath} + 0.190\vec{k})
\end{aligned}
\end{equation*}

In [12]:
np.set_printoptions(precision=3)
verAD = vAD/modAD
print('verAD = ',verAD)

verAD =  [0.619 0.762 0.19 ]


\begin{equation*}
\begin{aligned}
\vec{T}_\textrm{AE} = T_\textrm{AE}\vec{\lambda}_\textrm{AE}
= T_\textrm{AE}\frac{\vec{AE}}{||\vec{AE}||} =
T_\textrm{AE} (-0.215\vec{\imath} + 0.86\vec{\jmath} - 0.462\vec{k})
\end{aligned}
\end{equation*}

In [13]:
np.set_printoptions(precision=3)
verAE = vAE/modAE
print('verAE = ',verAE)

verAE =  [-0.215  0.86  -0.462]


Resultam assim os seguintes vetores no sistema de coordenadas
escolhido:

\begin{equation*}
\begin{cases}
\vec{T}_\textrm{AB} = Q(-0.438\vec{\imath} + 0.899\vec{\jmath}) \\
\vec{T}_\textrm{AC} = T_\textrm{AC}(0.8 \vec{\jmath} + 0.6\vec{k}) \\
\vec{T}_\textrm{AD} = Q (0.619\vec{\imath} + 0.762\vec{\jmath} + 0.190\vec{k})\\
\vec{T}_\textrm{AE} = T_\textrm{AE} (-0.215\vec{\imath} + 0.86\vec{\jmath} -
0.462\vec{k}) \\
\vec{P} = -P \vec{\jmath}
\end{cases}
\end{equation*}

Finalmente,

\begin{equation*}
\begin{cases}
\sum F_x = 0\\
\sum F_y = 0\\
\sum F_z = 0
\end{cases}\Leftrightarrow
\begin{cases}
(-0.438)Q + (0.619) Q + (-0.215)T_\textrm{AE} = 0 \\
(0.899)Q + (0.8)T_\textrm{AC} + (0.762)Q + (0.86)T_\textrm{AE} - P = 0 \\
(0.6)T_\textrm{AC} + (0.190) Q + (-0.462)T_\textrm{AE} = 0
\end{cases}
\end{equation*}

In [14]:
import sympy as sy
from sympy.solvers import solve

P = 1000 # unit: N
q, tac, tae = sy.symbols('q tac tae')

EQX = q*verAB[0] + q*verAD[0] + tae*verAE[0]
print('EQX : ',EQX)
EQY = q*verAB[1] + tac*verAC[1] + q*verAD[1] + tae*verAE[1] - P
print('EQY : ',EQY)
EQZ = tac*verAC[2] + q*verAD[2] + tae*verAE[2]
print('EQZ : ',EQZ)
sol = solve({EQX,EQY,EQZ},{q, tac, tae})

print(f'  P = {P:.1f} N')
Q = float(sol[q]); print(f'  Q = {Q:.1f} N')
TAD = float(sol[tac]); print(f'TAD = {TAD:.1f} N')
TAE = float(sol[tae]); print(f'TAE = {TAE:.1f} N')

EQX :  0.180845371856608*q - 0.21505376344086*tae
EQY :  1.66078116639914*q + 0.8*tac + 0.860215053763441*tae - 1000
EQZ :  0.19047619047619*q + 0.6*tac - 0.462365591397849*tae
  P = 1000.0 N
  Q = 377.6 N
TAD = 124.8 N
TAE = 317.5 N


### Apêncide. Categorias de equações de equilíbrio no plano (3D)

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/GFormulas/EQ3D1.jpg"
style="max-width: 100%;"/>


---

Copyright (c) DEMI - FCT NOVA

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>
